import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 1. Getting Started: Your main introduction page
    "intro",
    {
      type: "category",
      label: "Tutorial Basics",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-basics",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorial Extras",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-extras",
        },
      ],
    },

    // 2. Core Guides
    {
      type: "category",
      label: "Core Development Guides",
      collapsed: true,
      items: ["guides/docker-compose-guide"],
    },

    // 3. Technology Mastery
    {
      type: "category",
      label: "Java & Spring Boot",
      collapsed: true,
      items: ["java/jpa-database-setup", "java/unit-testing-basics"],
    },
    {
      type: "category",
      label: "Angular & TypeScript",
      collapsed: true,
      items: ["angular/state-management", "angular/tailwind-setup"],
    },
    {
      type: "category",
      label: "Rust",
      collapsed: true,
      items: ["rust/getting-started"],
    },
    {
      type: "category",
      label: "Python & Data",
      collapsed: true,
      items: ["python/fastapi-basics"],
    },
    {
      type: "category",
      label: "PostgreSQL Mastery",
      collapsed: true,
      items: ["database/optimization-techniques"],
    },
  ],
};

export default sidebars;
